---
title: "S01"
author: "Camilo Ramírez"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
require(readxl)

info_estudiantes <- read_excel("C:/Users/caramirezs/My Drive/PUJ/Esta(6102)/Conjunto de datos/Info_estudiantes.xlsx")

info_df <- data.frame(info_estudiantes)
```

```{r}
table(info_df$Carrera)
```

```{r}
tabla_salarios <- read.csv("ds_salaries.csv")
# View(tabla_salarios)
# convertir a dataframe
salarios_df <- data.frame(tabla_salarios)

valores = salarios_df$salary_in_usd
# Definir los puntos de corte para 5 intervalos
min_val <- min(valores)  # mínimo valor, que es 5132
max_val <- max(valores)  # máximo valor, que es 450000
breaks <- seq(from = min_val, to = max_val, length.out = 11)  # 11 puntos de corte para crear 5 intervalos

# Crear los intervalos
intervalos <- cut(valores, breaks, include.lowest = TRUE, dig.lab = 8)

# Ver los intervalos creados
table(intervalos)

```

```{r}
ceiling((324-75)/50)
```

# 29/01/2024

```{r}
# Importar los datos a trabajar
require(readxl)
info_House <- read.csv("[01] Conjunto de datos/kaggle/NY-House-Dataset.csv")
NY_House_df <- data.frame(info_House)
```

```{r}
sort(table(NY_House_df$TYPE), decreasing = TRUE)
tabla_frec_type <- sort(table(NY_House_df$TYPE), decreasing = TRUE)

library("RColorBrewer")

barplot(tabla_frec_type, main="Tipo de viviendas en NY", 
        xlab="Type", ylab="Número de viviendas", las=2,
        cex.names=0.7, cex.lab=0.9, cex.main=0.9, col=rainbow(7), horiz = F, 
        xpd = TRUE)



pie(tabla_frec_type,col=rainbow(7), border=F,main="Diagrama circular estudiantes",
    radius=1)

```

```{r}
valores = NY_House_df$PRICE
# Definir los puntos de corte para 5 intervalos
min_val <- min(valores)  
max_val <- max(valores)  
rango <- max_val - min_val
c(min_val, max_val, length(valores))
n_int <- ceiling(1 + log(length(NY_House_df$PRICE), 2))
anchura <- rango/n_int
print(c(n_int, anchura))
```

```{r}
breaks <- seq(from = min_val, to = max_val, length.out = (n_int+1))
breaks
```

```{r}
# Crear los intervalos
intervalos <- cut(valores, breaks, include.lowest = TRUE)
```

```{r}
# Ver los intervalos creados
table(intervalos)
```

```{r}
max_valor <- max(valores)
new_valores <- valores[valores != max_valor]
# Definir los puntos de corte para 5 intervalos
min_val <- min(new_valores)  
max_val <- max(new_valores)

rango <- max_val - min_val

c(min_val, max_val, length(new_valores))

n_int <- ceiling(1 + log(length(new_valores), 2))

anchura <- rango/n_int

print(c(n_int, anchura))

breaks <- seq(from = min_val, to = max_val, length.out = (n_int+1))

breaks

# Crear los intervalos
intervalos <- cut(valores, breaks, include.lowest = TRUE)

# Ver los intervalos creados
table(intervalos)
```

```{r}
# Encontrar los dos valores máximos en la lista
max_valores <- tail(sort(valores), 2)

new_valores <- valores[!valores %in% max_valores]
# Definir los puntos de corte para 5 intervalos
min_val <- min(new_valores)  
max_val <- max(new_valores)

rango <- max_val - min_val

c(min_val, max_val, length(new_valores))

n_int <- ceiling(1 + log(length(new_valores), 2))

anchura <- rango/n_int

print(c(n_int, anchura))

breaks <- seq(from = min_val, to = max_val, length.out = (n_int+1))

breaks

# Crear los intervalos
intervalos <- cut(valores, breaks, include.lowest = TRUE)

# Ver los intervalos creados
table(intervalos)

# Calcular la frecuencia de los intervalos
frecuencia_intervalos <- table(intervalos)

# Crear el gráfico de barras
barplot(frecuencia_intervalos, 
        main="Gráfico de Barras de Intervalos",
        xlab="Intervalos",
        ylab="Frecuencia",
        col=rainbow(length(frecuencia_intervalos)))

# Agregar etiquetas a las barras
text(barplot(frecuencia_intervalos), frecuencia_intervalos + 1, frecuencia_intervalos, pos = 3)

```

```{r}
# Crear el histograma
hist(new_valores, 
     breaks = breaks,  # Utiliza los mismos intervalos que calculaste anteriormente
     main = "Histograma de Valores",
     xlab = "Valores",
     ylab = "Frecuencia",
     col = "skyblue",  # Color de las barras
     border = "black",  # Color del borde de las barras
     xlim = c(min(new_valores), max(new_valores)))  # Establece el rango en el eje x
```

```{r}
# Establecer opciones para evitar la notación científica
options(scipen = 999)

# Crear el histograma
hist(new_valores, 
     breaks = breaks,  # Utiliza los mismos intervalos que calculaste anteriormente
     main = "Histograma de Valores",
     xlab = "Valores",
     ylab = "Frecuencia",
     col = "skyblue",  # Color de las barras
     border = "black",  # Color del borde de las barras
     xlim = c(min(new_valores), max(new_valores)))  # Establece el rango en el eje x
```

```{r}
# Obtener los valores de las barras del histograma
counts <- hist(new_valores, breaks = breaks, plot = FALSE)$counts

# Calcular las frecuencias acumuladas a partir de los datos del histograma
frecuencia_acumulada <- cumsum(counts)

# Crear la ojiva
plot(breaks[-length(breaks)], frecuencia_acumulada, type = "s", 
     main = "Ojiva",
     xlab = "Valores",
     ylab = "Frecuencia Acumulada",
     col = "blue")

# Agregar una línea de referencia en el eje x
abline(h = max(frecuencia_acumulada), col = "red", lty = 2)

# Etiquetar la línea de referencia
text(25, max(frecuencia_acumulada), "Valor Máximo", pos = 2, col = "red")
```

# 1/02/2024

```{r}
library(readxl)
Airport_Data_Speeds <- read_excel("[01] Conjunto de datos/Otros/32 - Airport Data Speeds.xlsx")
Airport_df <- data.frame(Airport_Data_Speeds)
Airport_df
```

```{r}
moda <- function(x) {
  tabla <- table(x)
  moda <- names(tabla[tabla == max(tabla)])
  if(length(moda) > 1) {
    return(as.numeric(moda))
  } else {
    return(as.numeric(moda))
  }
}
```

```{r}
sapply(Airport_df[, 2:5], mean, na.rm = TRUE)
sapply(Airport_df[, 2:5], median, na.rm = TRUE)
sapply(Airport_df[, 2:5], moda)
```

```{r}
sapply(Airport_df[, 2:5], mean, na.rm = TRUE)
```

```{r}
# Calcular moda y asegurar que el resultado sea uniforme
moda_resultados <- lapply(Airport_df[, 2:5], moda)
moda_combinada <- sapply(moda_resultados, function(x) {
  if(length(x) > 1) {
    paste(x, collapse = ", ")
  } else {
    x
  }
})


# Crear una tabla para las estadísticas utilizando los nombres de las columnas
estadisticas <- data.frame(
  Media = sapply(Airport_df[, 2:5], mean, na.rm = TRUE),
  Mediana = sapply(Airport_df[, 2:5], median, na.rm = TRUE),
  Moda = moda_combinada
)

estadisticas

  
```

```{r}

```

# 19/02

```{r}
library(readxl)
X32_Airport_Data_Speeds <- read_excel("[01] Conjunto de datos/Otros/32 - Airport Data Speeds.xlsx")
Airport_df <- data.frame(X32_Airport_Data_Speeds)
```

```{r}
install.packages("reshape2")
install.packages("ggplot2")
library(reshape2) # o library(tidyr) para pivot_longer
library(ggplot2)

```

```{r}
# Transformar los datos a formato largo
datos_long <- melt(Airport_df, id.vars = 'AIRPORT.CODE', variable.name = 'Company', value.name = 'Speed')
```

```{r}
# Crear el diagrama de cajas y bigotes
ggplot(datos_long, aes(x = Company, y = Speed, fill = Company)) +
  geom_boxplot(outlier.colour = "red") + # Resaltar los datos atípicos en rojo
  scale_fill_manual(values = c("VERIZON" = "blue", "SPRINT" = "green", "AT.T" = "yellow", "T.MOBILE" = "purple")) +
  labs(title = "Boxplot of Internet Speeds by Company with Outliers",
       x = "Company", y = "Internet Speed (Mbps)") +
  theme_minimal() # Un tema minimalista
```

```{r}
summary(Airport_df$VERIZON)
```

```{r}
bp_stats <- boxplot.stats(Airport_df$VERIZON) # Cambia VERIZON por la columna de interés

# Acceder a los resultados
bp_stats$stats # Estadísticas de la caja: mínimo, Q1, mediana (Q2), Q3, máximo
bp_stats$out # Valores atípicos
IQR(Airport_df$VERIZON) # Rango int
```

# 26/02: Distribuciones de probabilidad

```{r}
# Número de lanzamientos
n <- 10000

# Contadores para cada resultado
cara_cara <- 0
cara_cruz <- 0
cruz_cara <- 0
cruz_cruz <- 0

# Definir los posibles resultados de un lanzamiento de moneda
opciones <- c("Cara", "Cruz")

# Realizar n lanzamientos
for(i in 1:n) {
  # Simular el lanzamiento de dos monedas
  lanzamiento <- sample(opciones, size = 2, replace = TRUE)
  
  # Actualizar los contadores basados en los resultados
  if(lanzamiento[1] == "Cara" && lanzamiento[2] == "Cara") {
    cara_cara <- cara_cara + 1
  } else if(lanzamiento[1] == "Cara" && lanzamiento[2] == "Cruz") {
    cara_cruz <- cara_cruz + 1
  } else if(lanzamiento[1] == "Cruz" && lanzamiento[2] == "Cara") {
    cruz_cara <- cruz_cara + 1
  } else if(lanzamiento[1] == "Cruz" && lanzamiento[2] == "Cruz") {
    cruz_cruz <- cruz_cruz + 1
  }
}

# Mostrar los resultados
n0 <- cruz_cruz
n1 <- cara_cruz + cruz_cara
n2 <- cara_cara
cat('Total de eventos:', n, "\n")
cat("0: Frecuencias del evento: dos lanzamientos no caiga ninguna cara ", n0, "\n")
cat("1: Frecuencias del evento: dos lanzamientos caiga solo una cara ", n1, "\n")
cat("2: Frecuencias del evento: dos lanzamientos caigan dos caras ", n2, "\n")

eventos <- c(0, 1, 2)
frecuencias <- c(n0, n1, n2)
media_muestral<- sum(eventos*frecuencias)/n
varianza_muestral <- sum(frecuencias * (eventos - media_muestral)^2) / (n-1)
desviacion_estandar_muestral <- sqrt(varianza_muestral)
cat("media muestral:", media_muestral, "\ndesviacion estandar muestral:", desviacion_estandar_muestral, "\n\n")


# Probabilidades
cat("Probabilidades por aproximación de frecuencias relativas:\n")
cat("P(0): ", n0/n, "\n")
cat("P(1): ", n1/n, "\n")
cat("P(2): ", n2/n, "\n")
```

```{r}
n <- 10 
d <- 5
p <- 0.5
sum_prob <- 0
for(x in d:n) {
  prob <- choose(n, x) * 0.5^x * (1-0.5)^(n-x)
  sum_prob <- sum_prob + prob
  cat("Probabilidad de que exactamente", x, "lanzamientos sean cara: ", prob, "\n")
}
cat("Probabilidad de al menos", d, "lanzamientos sean cara: ", sum_prob, "\n")
```

```{r}
# Parámetros
n <- 460
p <- 0.5
x <- 252

prob_menos_de <- pbinom(x-1, size = n, prob = p) # P[X<=x]: x éxitos o menos
1- prob_menos_de

```

```{r}
print(dbinom(5:10, size=10, prob=0.5))
print(sum(dbinom(5:10, size=10, prob=0.5)))

```

```{r}
print(pbinom(5, size=10, prob=0.5)) # P[X<=5]: 5 exitos o menos
print(pbinom(4, size=10, prob=0.5, lower.tail = FALSE)) # P[X>4] más de 4 éxitos
```

```{r}
print(pbinom(2, size=2000, prob=2/2000))
```

# 03/04

```{r}
n<-8
p<-0.2
```

```{r}
x<-0:n
probabilidades  <- dbinom(x, n, p)
# Graficar la función de masa de probabilidad binomial
barplot(probabilidades, names.arg = x, col = "blue", 
        main = "Distribución Binomial",
        xlab = "Número de éxitos", ylab = "Probabilidad", 
        width = 1, # Ajusta este valor para cambiar el ancho de las barras
        space = 0)

# Agregar una curva normal para comparación (necesita ajuste debido a la base de barplot)
media <- n * p
desviacion <- sqrt(n * p * (1 - p))
curve(dnorm(x, mean = media, sd = desviacion), add = TRUE, col = "red", lwd = 2, xaxt = "n")

```

```{r}
prob <- dbinom(7, n, p)
cat("Probabilidad de que el número x de respuestas correctas sea exactamente 7 \n
    P(X=7) = ",prob)
```

```{r}
op1_prob <- sum(dbinom(4:n, n, p))
op2_prob <- pbinom(4, n, p, lower.tail = FALSE) + dbinom(4, n, p)

cat("OP1: Probabilidad de que el número x de respuestas correctas sea al menos 4 \n
    P(X>=4) = ",op1_prob)
cat("\n----\n")
cat("OP2: Probabilidad de que el número x de respuestas correctas sea al menos 4 \n
    P(X>=4) = ",op2_prob)
```

```{r}
op1_prob <- sum(dbinom(0:2, n, p))
op2_prob <- pbinom(3, n, p) - dbinom(3, n, p)
op3_prob <- pbinom(2, n, p)

cat("OP1: Probabilidad de que el número x de respuestas correctas sea menor que 3 \n
    P(X<3) = ",op1_prob)
cat("\n----\n")
cat("OP2: Probabilidad de que el número x de respuestas correctas sea menor que 3 \n
    P(X<3) = ",op2_prob)
cat("\n----\n")
cat("OP2: Probabilidad de que el número x de respuestas correctas sea menor que 3 \n
    P(X<3) = ",op3_prob)
```

```{r}
op1_prob <- sum(dbinom(0:2, n, p))
op2_prob <- pbinom(3, n, p) - dbinom(3, n, p)
op3_prob <- pbinom(2, n, p)

cat("OP1: Probabilidad de que el número x de respuestas correctas no sea mayor que 2 \n
    P(X<=2) = ",op1_prob)
cat("\n----\n")
cat("OP2: Probabilidad de que el número x de respuestas correctas sea menor que 3 \n
    P(X<=2)) = ",op2_prob)
cat("\n----\n")
cat("OP2: Probabilidad de que el número x de respuestas correctas sea menor que 3 \n
    P(X<=2) = ",op3_prob)
```

```{r}
prob <- dbinom(0, n, p)
cat("Probabilidad de no tener respuestas correctas \n
    P(X=0) = ",prob)
```

```{r}
op1_prob <- sum(dbinom(1:n, n, p))
op2_prob <- 1 - dbinom(0, n, p)
op3_prob <- pbinom(0, n, p, lower.tail = FALSE)

cat("OP1: Probabilidad de que al menos una respuesta sea correcta \n
    P(X>=1) = ",op1_prob)
cat("\n----\n")
cat("OP1: Probabilidad de que al menos una respuesta sea correcta \n
    P(X>=1) = ",op2_prob)
cat("\n----\n")
cat("OP1: Probabilidad de que al menos una respuesta sea correcta \n
    P(X>=1) = ",op3_prob)
```

```{r}
n<-90
p<-0.27
x<-0:n
probabilidades  <- dbinom(x, n, p)
# Graficar la función de masa de probabilidad binomial
barplot(probabilidades, names.arg = x, col = "blue", 
        main = "Distribución Binomial",
        xlab = "Número de éxitos", ylab = "Probabilidad", 
        width = 1, # Ajusta este valor para cambiar el ancho de las barras
        space = 0)

# Agregar una curva normal para comparación (necesita ajuste debido a la base de barplot)
media <- n * p
desviacion <- sqrt(n * p * (1 - p))
curve(dnorm(x, mean = media, sd = desviacion), add = TRUE, col = "red", lwd = 2, xaxt = "n")
```

```{r}
prob  <- pbinom(7, n, p)
cat("Probabilidad de obtener 7 o menos minorías 
    P(X<=7) = ",prob)
```

```{r}
media <- n*p
var <- n*p*(1-p)
desvest <- sqrt(var)

cat("media: ", media, "\n", "desviación estándar: ", desvest)
```

```{r}
sig_altos <- media + 2*desvest
sig_bajo <- media - 2*desvest

cat("los resultados significativamente bajos deben ser menor o igual a: ", sig_bajo, "\n", "los resultados significativamente bajos deben ser mayor o igual a: ", sig_altos)
```

```{r}
n<-20
p<-0.79
x<-0:n
probabilidades  <- dbinom(x, n, p)
# Graficar la función de masa de probabilidad binomial
barplot(probabilidades, names.arg = x, col = "blue", 
        main = "Distribución Binomial",
        xlab = "Número de éxitos", ylab = "Probabilidad", 
        width = 1, # Ajusta este valor para cambiar el ancho de las barras
        space = 0)

# Agregar una curva normal para comparación (necesita ajuste debido a la base de barplot)
media <- n * p
desviacion <- sqrt(n * p * (1 - p))
curve(dnorm(x, mean = media, sd = desviacion), add = TRUE, col = "red", lwd = 2, xaxt = "n")
```

```{r}
prob  <- pbinom(19, n, p)
cat("Probabilidad de obtener 19 o más 
    P(X<=19) = ",prob)
```

```{r}
media <- n*p
var <- n*p*(1-p)
desvest <- sqrt(var)

cat("media: ", media, "\n", "desviación estándar: ", desvest)

sig_altos <- media + 2*desvest
sig_bajo <- media - 2*desvest

cat("los resultados significativamente bajos deben ser menor o igual a: ", sig_bajo, "\n", "los resultados significativamente bajos deben ser mayor o igual a: ", sig_altos)
```

```{r}
n<-6
p<-0.2
x<-0:n
probabilidades  <- dbinom(x, n, p)
# Graficar la función de masa de probabilidad binomial
barplot(probabilidades, names.arg = x, col = "blue", 
        main = "Distribución Binomial",
        xlab = "Número de éxitos", ylab = "Probabilidad", 
        width = 1, # Ajusta este valor para cambiar el ancho de las barras
        space = 0)

# Agregar una curva normal para comparación (necesita ajuste debido a la base de barplot)
media <- n * p
desviacion <- sqrt(n * p * (1 - p))
curve(dnorm(x, mean = media, sd = desviacion), add = TRUE, col = "red", lwd = 2, xaxt = "n")
```

```{r}
prob  <- dbinom(5, n, p)
cat("Probabilidad de obtener exactamente 5 
    P(X=5) = ",prob)
```

```{r}
prob  <- dbinom(6, n, p)
cat("Probabilidad de obtener exactamente 6
    P(X=6) = ",prob)
```
